# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Install build dependencies and source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN apk add --no-cache git python3 make g++ \
 && npm install \
 && npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app
# Copy built code and production dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Ensure output directory exists
RUN mkdir -p /app/output

ENV NODE_ENV=production
ENTRYPOINT ["node", "build/index.js"]
